name: static analysis

on:
  workflow_call:
  workflow_dispatch:  # Manual trigger

jobs:

  code-analysis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python-version: ["3.10",]  # maya 2024

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint mypy

    - name: Analysing the code with pylint
      run: |
        pylint src

    - name: Analysing the code with black
      uses: psf/black@stable
      with:
        src: "src"
        options: "--diff"

    - name: Analysing the code with mypy
      run: mypy src